[package]
name = "enygmah"
version = "0.1.0"
edition = "2021"
description = "Automate vulnerability analysis within several tools"
homepage = "https://github.com/hotaydev/enygmah"
repository = "https://github.com/hotaydev/enygmah"
documentation = "https://github.com/hotaydev/enygmah"
license = "AGPL-3.0"
readme = "README.md"
keywords = ["security", "vulnerability", "analysis"]
publish = false

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
env_logger = "0.11.5"
