name: Feature request
description: Suggest a new idea for enygmah.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using enygmah!

        If you are looking for support, please check out our documentation
        or consider asking a question on our Github Discussions Page:

          - https://github.com/hotaydev/enygmah/wiki
          - https://github.com/hotaydev/enygmah/discussions/categories/q-a
  - type: markdown
    attributes:
      value: |
        Before filling the form fields, please consider the following:
        - Ensure that you have searched the [existing issues](https://github.com/hotaydev/enygmah/issues)
        - Read the "Submit an Issue" section of our [Contributing Guide](https://github.com/hotaydev/enygmah/blob/main/CONTRIBUTING.md#submit-an-issue)
  - type: textarea
    attributes:
      label: Use case
      description: |
        Please tell us the problem you are running into that led to you wanting
        a new feature.

        Is your feature request related to a problem? Please give a clear and
        concise description of what the problem is.

        Describe the alternative solutions you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: |
        Briefly but precisely describe what you would like enygmah to be able to do.

        Consider attaching something showing what you are imagining:
         * images
         * videos
         * code samples
    validations:
      required: true
