blank_issues_enabled: true
contact_links:
  - name: Help from the Discord channel
    url: https://discord.gg/KvVc32G6
    about: Ask your questions about how to achieve a particular effect using enygmah or get other type of help from the community.